pipeline {
    agent any

    environment {
        // 공통 환경 변수
        GITLAB_CREDENTIALS_ID = "gitlab"
        GITLAB_REPO = "https://lab.ssafy.com/s11-final/S11P31A309.git"
        BRANCH = "be"
 
        SSH_CREDENTIALS_ID = "ssafy-ec2-user"
        SERVER_IP = "43.201.33.45"
    }

    stages {
        stage('Shutdown') {
            parallel {
                stage('Java Docker Build') {
                    steps {
                        sh 'docker container rm -f backend-app'
                    }
                }
            }
        }
        
        stage('Github clone') {
            steps {
                git branch: "${BRANCH}",
                credentialsId: "${GITLAB_CREDENTIALS_ID}",
                url: "${GITLAB_REPO}"
            }
        }
        
        stage('Build') {
            parallel {
                stage('Java Build') {
                    steps {
                        dir('./backend') {
                            sh 'sh gradlew build'
                        }
                    }
                }
            }
        }
        
        stage('Docker Build') {
            parallel {
                stage('Java Docker Build') {
                    steps {
                        dir('./backend') {
                            sh 'docker build -t backend . '
                        }
                    }
                }
            }
        }

        stage('Create Volume') {
            steps {
                sh 'docker volume create data'
            }
        }
            
        stage('Docker Run') {
            parallel {
                stage('Java Docker Run') {
                    steps {
                        dir('./backend') {
                            sh 'docker run --name backend-app -d -v data:/data -p 8080:8080 backend'
                        }
                    }
                }
            }
        }
    }

}