spring:
  jackson:
    time-zone: Asia/Seoul
  data:
    redis:
      host: 43.201.33.45  # Redis 서버 호스트
      port: 6379      # Redis 서버 포트
      password: roWjsmsvmffpdl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: a309
    password: todwjsrhdls
    url: jdbc:mysql://43.201.33.45:3306/free?serverTimezone=Asia/Seoul&useUnicode=true&character_set_server=utf8mb4

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
          format_sql: true
    show-sql: true

jwt:
    secret : 5543db1f2e54b5626c948f4cf35481aa1fb3f43446ac583aacdabf46afc3a81d946388442fd5c9e6df0fce58d4f877a8467cbe3095ef40cd2e877f9a586a00a7
    expiration : 4320000
    refreshexpiration : 25920000

cloud:
  aws:
    s3:
      bucket: bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
        accessKey: key
        secretKey: secret

coolsms:
  apikey: apikey
  apisecret: secret
  fromnumber: phone
    #전화번호는 '-' 빼고

cors:
  allowed-origins: http://localhost:3000,http://localhost:8080,http://k11a309.p.ssafy.io:3000, http://k11a309.p.ssafy.io

fastApi:
  url: http://k11a309.p.ssafy.io:8000/
